name: 番茄看看

on:
  workflow_dispatch:
  schedule:
     - cron: '15 12,14,16,20 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        fqkkurl: ${{ secrets.fqkkurl }}      	
        fqkkhd: ${{ secrets.fqkkhd }}  
      
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/2017bigb/ziye.git ~/ziye
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.fqkkhd
        run: |
          cd ~/ziye
          git checkout feizao
          npm install
      - name: '运行 【番茄看看】'
        if: env.fqkkhd
        run: |
          cd ~/ziye
          node Task/fqkk.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
