name: 番茄看看

on:
  workflow_dispatch:
  schedule:
     - cron: '15 12,14,16,20 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        fqkkurl: ${{ secrets.FQKK_URL }}
        fqkkhd: ${{ secrets.FQKK_HD }}   
      
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/2017bigb/yangmao.git ~/yangmao
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.fqkkhd
        run: |
          cd ~/yangmao
          git checkout feizao
          npm install
      - name: '运行 【番茄看看】'
        if: env.fqkkhd
        run: |
          cd ~/yangmao
          node fqkk.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
